BlogPhoto/Models/Photo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace BlogPhoto.Models
{
    public class Photo
    {
        public Photo()
        {
            HashTags = new List<HashTag>();
        }
        public int Id { get; set; }

        public string PhotoTitle { get; set; }

        public string Description { get; set; }

        public DateTime LoadTime { get; set; }
        public string HashTag { get; set; }
        public string ImagePath { get; set; }

        public int HashTagId { get; set; }
        
        public virtual ICollection<HashTag> HashTags { get; set; }
    }
}

BlogPhoto/Areas/Admin/Controllers/PhotosController.cs
using BlogPhoto.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogPhoto.Areas.Admin.Controllers
{
    public class PhotosController : AdminBaseController
    {
        // GET: Admin/Photos
        public ActionResult Index()
        {
            return View(db.Photos.ToList());
        }

        public ActionResult Add()
        {
            ViewBag.HashTag = new SelectList(db.HashTags, "Id", "HashTagName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(Photo photo, HttpPostedFileBase image, int[] Id)
        {
            //https://www.mikesdotnetting.com/article/265/asp-net-mvc-dropdownlists-multiple-selection-and-enum-support
            ResimHataKontrolleri(image);
            if (ModelState.IsValid)
            {
                photo.ImagePath = ResimYukle(image);
                db.Photos.Add(photo);
                if (Id != null)
                {
                    for (int i = 0; i < Id.Length; i++)
                    {
                        HashTag hashTag = db.HashTags.Find(Id[i]);
                        photo.HashTags.Add(hashTag);
                    }
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.HashTag = new SelectList(db.HashTags, "Id", "HashTagName");
            return View();
        }

        public ActionResult Edit(int id)
        {
            var photo = db.Photos.Find(id);
            if (photo == null) return HttpNotFound();
            ViewBag.HashTagId = new SelectList(db.HashTags, "Id", "HashTagName");
            return View(photo);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Photo photo, HttpPostedFileBase image, bool resmiKaldir)
        {
            ResimHataKontrolleri(image);
            if (ModelState.IsValid)
            {
                var resimYolu = ResimYukle(image);
                if (resimYolu != null || resmiKaldir)
                {
                    ResimSil(photo.ImagePath);  
                    photo.ImagePath = resimYolu;
                }
                db.Entry(photo).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.HashTagId = new SelectList(db.HashTags, "Id", "HashTagName");
            return View(photo);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            var image = db.Photos.Find(id);
            if (image == null) return HttpNotFound();

            db.Photos.Remove(image);
            db.SaveChanges();
            ResimSil(image.ImagePath);
            TempData["mesaj"] = $"\"{image.PhotoTitle}\" adlı ürün başarıyla silindi."; //TempData sayfalar arası 1 kerelik veri taşır.
            return RedirectToAction("Index");

        }

        private void ResimSil(string resimYolu)
        {
            if (!string.IsNullOrEmpty(resimYolu))
            {
                var silYolu = Path.Combine(Server.MapPath("~/Images/Uploads"), resimYolu);

                if (System.IO.File.Exists(silYolu))
                {
                    System.IO.File.Delete(silYolu);
                }
            }
        }
        private void ResimHataKontrolleri(HttpPostedFileBase resim)
        {
            string[] izinVerilenler = { ".jpg", ".jpeg", ".png" };
            if (resim != null)
            {
                if (!izinVerilenler.Contains(Path.GetExtension(resim.FileName).ToLower()))
                {
                    ModelState.AddModelError("resim", "İzin verilen dosya uzantıları: jpg/jpeg, png");
                }

                else if (resim.ContentLength > 1000 * 1000)
                {
                    ModelState.AddModelError("resim", "Maksimum resim boyutu:1mb olmalıdır.");
                }
            }
        }

        private string ResimYukle(HttpPostedFileBase resim)
        {
            if (resim == null)
                return null;

            var dosyaAd = Guid.NewGuid().ToString() + Path.GetExtension(resim.FileName);
            var yuklemeKlasoruYolu = Server.MapPath("~/Images/Uploads");
            var kaydetYol = Path.Combine(yuklemeKlasoruYolu, dosyaAd);
            resim.SaveAs(kaydetYol);
            return dosyaAd;
        }
    }
}

BlogPhoto/Areas/Admin/Views/Photos/Add.cshtml
@model Photo
@{
    ViewBag.Title = "Add";
}

<h2>Add new Photo</h2>

@using (Html.BeginForm("Add", "Photos", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(x => x.PhotoTitle)
        @Html.TextBoxFor(x => x.PhotoTitle, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.PhotoTitle)
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.Description)
        @Html.TextBoxFor(x => x.Description, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Description)
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.LoadTime)
        @Html.TextBoxFor(x => x.LoadTime, new { type = "datetime-local", @class = "form-control" })
        @Html.ValidationMessageFor(x => x.LoadTime)
    </div>
    <div class="form-group">
        @Html.DropDownList("hasTagId",( MultiSelectList)ViewBag.HashTag, new { multiple="multiple", @class ="form-control"})
       
        @*@Html.LabelFor(x => x.HashTag)
        @Html.DropDownListFor(x => x.HashTagId, null, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.HashTagId)*@
    </div>

    <div class="form-group">
        <label for="resim">Görsel:</label>
        <input type="file" id="image" name="image" />
        @Html.ValidationMessage("image")
    </div>
    <button>Ekle</button>
}

BlogPhoto/Areas/Admin/Views/Photos/Edit.cshtml
@model Photo
@{
    ViewBag.Title = "Edit";
}

<h2>Edit Photo</h2>

@using (Html.BeginForm("Edit", "Photos", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.HiddenFor(x => x.ImagePath)
        @Html.Hidden("ResmiKaldir", false)
        <label for="image">Görsel:</label>
        <div style="margin-bottom:.5rem" id="gorsel">
            @if (!string.IsNullOrEmpty(Model.ImagePath))
            {
                <img src="~/Images/Uploads/@Model.ImagePath" alt="@Model.ImagePath" width="100" height="100" /> <br />
                <a href="#" id="btnResmiKaldir">Resmi Kaldır</a>
            }
            else
            {
                <i class="fas fa-image" style="font-size:50px; color:gray;"></i>
            }
        </div>
        <input type="file" id="image" name="image" />
        @Html.ValidationMessage("image")
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.PhotoTitle)
        @Html.TextBoxFor(x => x.PhotoTitle, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.PhotoTitle)
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.Description)
        @Html.TextBoxFor(x => x.Description, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Description)
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.LoadTime)
        @Html.TextBoxFor(x => x.LoadTime, new { type = "datetime-local", @class = "form-control" })
        @Html.ValidationMessageFor(x => x.LoadTime)
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.HashTagId)
        @Html.DropDownListFor(x => x.HashTagId, null, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.HashTagId)
    </div>

    @Html.HiddenFor(x => x.Id)
    <button>Kaydet</button>
}
@section scripts{
    <script>
        $("#btnResmiKaldir").click(function (event) {
            event.preventDefault();
            $("#ResmiKaldir").val("true");
            $("#gorsel").hide();
        });
    </script>
}

BlogPhoto/Areas/Admin/Views/Photos/Index.cshtml
@model List<Photo>
@{
    ViewBag.Title = "Index";
}

<h2>Photos</h2>

<a href="@Url.Action("Add")">
    <i class="fas fa-plus"> </i>
    New Photo
</a>

<table class="table">
    <thead>
        <tr>
            <th>Photo</th>
            <th>Photo Title</th>
            <th>Description</th>
            <th>LoadTime</th>
            <th>HashTag</th>
            <th>Operations</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @if (!string.IsNullOrEmpty(item.ImagePath))
                    {
                        <img src="~/Images/Uploads/@item.ImagePath" alt="@item.PhotoTitle" width="50" height="50" />
                    }
                    else
                    {
                        <i class="fas fa-image" style="font-size:50px; color:gray;"></i>
                    }
                </td>
                <td>@item.PhotoTitle</td>
                <td>@item.Description</td>
                <td>@item.LoadTime</td>
                <td>
                    @foreach (var hashTag in item.HashTags)
                    {
                        <span>#</span>@hashTag.HashTagName

                    }
                </td>
                <td>
                    <form method="post" action="@Url.Action("Delete","Photos")" style="display:inline">
                        @Html.AntiForgeryToken()
                        <input type="hidden" name="id" value="@item.Id" />
                        <button class="btn btn-sm btn-danger">Delete</button>
                    </form>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-warning" })
                </td>
            </tr>
        }
    </tbody>
</table>