BlogPhoto/Models/HashTag.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BlogPhoto.Models
{
    public class HashTag
    {
        public HashTag()
        {
            Photos = new List<Photo>();
        }
        public int Id { get; set; }
        public string HashTagName { get; set; }
        public virtual ICollection<Photo> Photos { get; set; }
    }
}

BlogPhoto/Areas/Admin/Controllers/HashTagsController.cs
using BlogPhoto.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogPhoto.Areas.Admin.Controllers
{
    public class HashTagsController : AdminBaseController
    {
        // GET: Admin/HashTags
        public ActionResult Index()
        {
            return View(db.HashTags.ToList());
        }
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(HashTag hashTag)
        {
            if (ModelState.IsValid)
            {
                db.HashTags.Add(hashTag);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }


        public ActionResult Edit(int id)
        {
            var hashTag = db.HashTags.Find(id);
            if (hashTag == null) return HttpNotFound();
            return View(hashTag);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(HashTag hashTag)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hashTag).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            var hashTag = db.HashTags.Find(id);
            if (hashTag == null)
            {
                return HttpNotFound();
            }
            db.HashTags.Remove(hashTag);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

BlogPhoto/Areas/Admin/Views/HashTags/Add.cshtml
@model HashTag
@{
    ViewBag.Title = "Add";
}

<h2>Add new HashTag</h2>

@using (Html.BeginForm("Add", "HashTags", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        @Html.LabelFor(x => x.HashTagName)
        @Html.TextBoxFor(x => x.HashTagName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.HashTagName)
    </div>
    <button>Add</button>
}

BlogPhoto/Areas/Admin/Views/HashTags/Edit.cshtml
@model HashTag
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "HashTags", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        @Html.LabelFor(x => x.HashTagName)
        @Html.TextBoxFor(x => x.HashTagName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.HashTagName)
    </div>

    @Html.HiddenFor(x => x.Id)
    <button>Save</button>
}

BlogPhoto/Areas/Admin/Views/HashTags/Index.cshtml
@model List<HashTag>
@{
    ViewBag.Title = "Index";
}

<h2>HashTags</h2>


<a href="@Url.Action("Add")">
    <i class="fas fa-plus"> </i>
    New HashTag
</a>
<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>HashTag Name</th>
            <th>Operations</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.HashTagName</td>
                <td>
                    <form method="post" action="@Url.Action("Delete","HashTags")" style="display:inline">
                        @Html.AntiForgeryToken()
                        <input type="hidden" name="id" value="@item.Id" />
                        <button class="btn btn-sm btn-danger">Delete</button>
                    </form>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-warning" })
                </td>
            </tr>
        }
    </tbody>
</table>